networks:
  default: testnet_bradbury

  testnet_bradbury:
    url: "https://rpc-bradbury.genlayer.com"
    chain_type: "testnet_bradbury"

paths:
  contracts: "contracts"
  artifacts: "artifacts"

environment: .env
